### PR TITLE
Bugfix theme upload

### PR DESCRIPTION
**Pull request by csaunders**
This fixes upload such that a request to upload will upload all files instead of having to specify the exact files.

- Also fixes a bug with git repositories
- Makes filters work within the theme client so filtering should come for free now

### CODE REVIEW

**Comment by bman-80stees** [comment]
Will this be available for windows x64 download? I'm not sure how to apply a patch to the current version I have.

**Comment by csaunders** [comment]
Just replace the binary.

**Comment by bman-80stees** [comment]
I had downloaded the file from the downloads area and had to append  the .exe to the end. I'm not that familiar with git and binaries.

**Comment by bman-80stees** [comment]
I found where I needed to be, thanks again for these fixes!

**Comment by csaunders** [comment]
I just fixed the build script so future releases shouldn't have that missing `.exe` file extension anymore.

**Comment by bman-80stees** [comment]
Thanks!

**Pull request merged**
